### ISSUE TITLE
User Story: Profile Creation

### ISSUE THREAD

**Issue by fsjavier** [fsjavier/hoodsap-api#1]
As a developer I want a new profile to be automatically created when a user register

## Acceptance Criteria
AC1: After a user registers a new profile is created
AC2: The display_name field is automatically populated with the username

## Tasks:
- [ ] Create profiles app
- [ ] Add profiles model and signals to automatically create the profile
- [ ] Override save method to populate display_name with username
