### ISSUE TITLE
User Story: Post and event tags

### ISSUE THREAD

**Issue by fsjavier** [fsjavier/hoodsap-api#14]
As a developer I want to enable users to create, read and delete tags for post and events if it's their own

## Acceptance Criteria
AC1: A GET request to the tags endpoint lists all tags
AC2: A POST request to the tags endpoint creates a new tag only if the user is registered
AC3: A DELETE request to the specific tags endpoint deletes the tag only if it's their own

## Tasks:
- [x] Create the tags app
- [x] Create the tags model and serializer
- [x] Create list and detail views
- [x] Restrict create access to registered users
- [x] Restrict delete access to tags' owner
