### ISSUE TITLE
User Story: Conditional navigation menu

### ISSUE THREAD

**Issue by fsjavier** [fsjavier/hoodsap-api#22]
As a user I can see a different navigation menu when I'm logged in / out so that I can easy identify my state

## Acceptance Criteria
AC1: Icons in the navigation menu clearly indicate if the user is logged in / out

## Tasks:
- [x] Create navbar component
- [x] Add routes to project
- [x] Get the current user and check if they are logged in
- [x] Conditionally render elements depending on the user's state
