### ISSUE TITLE
User Story: Select location

### ISSUE THREAD

**Issue by fsjavier** [fsjavier/hoodsap-api#24]
As a registered user I can select a location so that my posts are specific to a neighborhood.

## Acceptance Criteria
AC1: When the user clicks on location a map is displayed where the user can select a location
AC2: The location chosen is displayed to the user
AC3: If the user confirms the location is saved and can be send with the form

## Tasks:
- [ ] Add maps library to the project
- [ ] Handle selecting a location on the map
- [ ] Perform reverse geocoding to get neighborhood, city and country from coordinated.
- [ ] Save the location instance
- [ ] Get the location instance to be used in the form
- [ ] Add the location instance to the form
