### ISSUE TITLE
User Story: Profiles views

### ISSUE THREAD

**Issue by fsjavier** [fsjavier/hoodsap-api#3]
As a developer I want users to access all profiles but only be able to edit their own

## Acceptance Criteria
AC1: users can access the endpoint to list all profiles
AC2: users can access detail view of a profile
AC3: only the owner of the profile can edit it

## Tasks:
- [x] Create profiles serializer
- [x] Create profiles urls
- [x] Create profiles list view and detail view
- [x] Create IsOwnerOrReadOnly permission and add it to detail view
