### ISSUE TITLE
User Story: Avoid unnecessary token refresh request

### ISSUE THREAD

**Issue by fsjavier** [fsjavier/hoodsap-api#35]
As a developer I want to avoid sending unnecessary requests to the API so that the session is optimised

## Acceptance Criteria
AC1: Logged out users don't make refresh token requests

## Tasks:
- [x] Install jwt-decode library
- [x] Store refresh token in local storage
- [x] Check if the token exists before sending a refresh request
