### ISSUE TITLE
User Story: Create events

### ISSUE THREAD

**Issue by fsjavier** [fsjavier/hoodsap-api#36]
As a registered user I can create an event so that I can share it with everyone else

## Acceptance Criteria
AC1: Display create event button
AC2: Load create event form
AC3: After the event is created it's automatically displayed

## Tasks:
- [x] Add form page
- [x] Create route to form
- [x] Style form page
- [x] Send POST request to API and handle errors
