### ISSUE TITLE
User Story: Events list

### ISSUE THREAD

**Issue by fsjavier** [fsjavier/hoodsap-api#38]
As a user I can see a list with all events so that I can scroll through the content

## Acceptance Criteria
AC1: Events are fetched and displayed
AC2: The first 10 events load
AC3: As the user keeps scrolling down new events are loaded
AC4: Event should be displayed with the most recent first

## Tasks:
- [] Add EventsPage component and create route
- [ ] Add filter and search to events GET request
- [ ] Add infinite scroll logic
