### ISSUE TITLE
User Story: Edit and delete events

### ISSUE THREAD

**Issue by fsjavier** [fsjavier/hoodsap-api#41]
As a logged in user I can edit and delete my own events so that I can control my content

## Acceptance Criteria
AC1: In the event details the user can see the option to delete and edit an own event
AC2: Events owned by other users don't have the option
AC3: Before deleting an event the user needs to confirm their choice

## Tasks:
- [ ] Add dropdown menu component when the user is the owner
- [ ] Redirect user to edit page when clicking on edit icon
- [ ] Add edit form
- [ ] Show delete confirmation modal when clicking on delete
- [ ] Add confirmation modal
- [ ] After confirming deletion send delete request and redirect the user to previous page
