### ISSUE TITLE
User Story: Filter posts based on location

### ISSUE THREAD

**Issue by fsjavier** [fsjavier/hoodsap-api#43]
As a user I can filter the posts and events based on my location so that I can see only the ones that are relevant to me

## Acceptance Criteria
AC1: The user can filter the posts with a slider
AC2: The slider shows the distance to the user
AC3: Posts are filtered based on the user's location, posts location and distance filter

## Tasks:
- [ ] Add form for the user to select the radius
- [ ] Add slider component to the form
- [ ] Send request to fetch posts based on user's latitude, longitude and radius
