### ISSUE TITLE
User Story: Location for profiles and posts

### ISSUE THREAD

**Issue by fsjavier** [fsjavier/hoodsap-api#7]
As a developer I want to add location functionality to be consumed by different parts of the application (profiles, posts, events)

## Acceptance Criteria
AC1: Check if location already exists and set it if it doesn't
AC2: Location can be updated

## Tasks:
- [ ] Create a location app
- [ ] Create a location model and serializer
- [ ] Create views to retrieve and update a user's location
