### ISSUE TITLE
User Story: User Post Comments

### ISSUE THREAD

**Issue by fsjavier** [fsjavier/hoodsap-api#8]
As a developer I want to enable users to create, read, update and delete comments if it's their own

## Acceptance Criteria
AC1: A GET request to the comments endpoint lists all comments
AC2: A POST request to the comments endpoint creates a new comment only if the user is registered
AC3: A PUT request to the specific comment endpoint updates the comment only if it's their own
AC4: A DELETE request to the specific comment endpoint deletes the comment only if it's their own

## Tasks:
- [x] Create the comments app
- [x] Create the comments model and serializer
- [x] Create list and detail views
- [x] Restrict create access to registered users
- [x] Restrict update, delete access to comments' owner
