### ISSUE TITLE
User Story: User likes

### ISSUE THREAD

**Issue by fsjavier** [fsjavier/hoodsap-api#9]
As a developer I want to enable users to create, read and delete likes if it's their own

## Acceptance Criteria
AC1: A GET request to the likes endpoint lists all likes
AC2: A POST request to the comments endpoint creates a new like only if the user is registered
AC3: A DELETE request to the specific like endpoint deletes the like only if it's their own

## Tasks:
- [ ] Create the likes app
- [ ] Create the likes model and serializer
- [ ] Create list and detail views
- [ ] Restrict create access to registered users
- [ ] Restrict delete access to likes' owner
